# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CritterCrush' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.0'

  # Pods for CritterCrush

  target 'CritterCrushTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CritterCrushUITests' do
    # Pods for testing
  end

end
